In [1]:
# Importing and loading the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
appointments = pd.read_csv("C:/Users/ROBERT/Desktop/ML-Assignments/KaggleV2-May-2016.csv")

### Inspecting the dataset

In [2]:
appointments.head()

PatientId  AppointmentID Gender          ScheduledDay  \
0  2.987250e+13        5642903      F  2016-04-29T18:38:08Z   
1  5.589978e+14        5642503      M  2016-04-29T16:08:27Z   
2  4.262962e+12        5642549      F  2016-04-29T16:19:04Z   
3  8.679512e+11        5642828      F  2016-04-29T17:29:31Z   
4  8.841186e+12        5642494      F  2016-04-29T16:07:23Z   

         AppointmentDay  Age      Neighbourhood  Scholarship  Hipertension  \
0  2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0             1   
1  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             0   
2  2016-04-29T00:00:00Z   62      MATA DA PRAIA            0             0   
3  2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0             0   
4  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             1   

   Diabetes  Alcoholism  Handcap  SMS_received No-show  
0         0           0        0             0      No  
1         0           0        0             0      No  
2         0           0        0             0      No  
3         0           0        0             0      No  
4         1           0        0             0      No

In [3]:
appointments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64  
 2   Gender          110527 non-null  object 
 3   ScheduledDay    110527 non-null  object 
 4   AppointmentDay  110527 non-null  object 
 5   Age             110527 non-null  int64  
 6   Neighbourhood   110527 non-null  object 
 7   Scholarship     110527 non-null  int64  
 8   Hipertension    110527 non-null  int64  
 9   Diabetes        110527 non-null  int64  
 10  Alcoholism      110527 non-null  int64  
 11  Handcap         110527 non-null  int64  
 12  SMS_received    110527 non-null  int64  
 13  No-show         110527 non-null  object 
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB


In [4]:
appointments.iloc[0:10]

PatientId  AppointmentID Gender          ScheduledDay  \
0  2.987250e+13        5642903      F  2016-04-29T18:38:08Z   
1  5.589978e+14        5642503      M  2016-04-29T16:08:27Z   
2  4.262962e+12        5642549      F  2016-04-29T16:19:04Z   
3  8.679512e+11        5642828      F  2016-04-29T17:29:31Z   
4  8.841186e+12        5642494      F  2016-04-29T16:07:23Z   
5  9.598513e+13        5626772      F  2016-04-27T08:36:51Z   
6  7.336882e+14        5630279      F  2016-04-27T15:05:12Z   
7  3.449833e+12        5630575      F  2016-04-27T15:39:58Z   
8  5.639473e+13        5638447      F  2016-04-29T08:02:16Z   
9  7.812456e+13        5629123      F  2016-04-27T12:48:25Z   

         AppointmentDay  Age      Neighbourhood  Scholarship  Hipertension  \
0  2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0             1   
1  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             0   
2  2016-04-29T00:00:00Z   62      MATA DA PRAIA            0             0   
3  2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0             0   
4  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             1   
5  2016-04-29T00:00:00Z   76          REPÚBLICA            0             1   
6  2016-04-29T00:00:00Z   23         GOIABEIRAS            0             0   
7  2016-04-29T00:00:00Z   39         GOIABEIRAS            0             0   
8  2016-04-29T00:00:00Z   21         ANDORINHAS            0             0   
9  2016-04-29T00:00:00Z   19          CONQUISTA            0             0   

   Diabetes  Alcoholism  Handcap  SMS_received No-show  
0         0           0        0             0      No  
1         0           0        0             0      No  
2         0           0        0             0      No  
3         0           0        0             0      No  
4         1           0        0             0      No  
5         0           0        0             0      No  
6         0           0        0             0     Yes  
7         0           0        0             0     Yes  
8         0           0        0             0      No  
9         0           0        0             0      No

### Checking for null values

In [5]:
appointments.isnull()

PatientId  AppointmentID  Gender  ScheduledDay  AppointmentDay    Age  \
0           False          False   False         False           False  False   
1           False          False   False         False           False  False   
2           False          False   False         False           False  False   
3           False          False   False         False           False  False   
4           False          False   False         False           False  False   
...           ...            ...     ...           ...             ...    ...   
110522      False          False   False         False           False  False   
110523      False          False   False         False           False  False   
110524      False          False   False         False           False  False   
110525      False          False   False         False           False  False   
110526      False          False   False         False           False  False   

        Neighbourhood  Scholarship  Hipertension  Diabetes  Alcoholism  \
0               False        False         False     False       False   
1               False        False         False     False       False   
2               False        False         False     False       False   
3               False        False         False     False       False   
4               False        False         False     False       False   
...               ...          ...           ...       ...         ...   
110522          False        False         False     False       False   
110523          False        False         False     False       False   
110524          False        False         False     False       False   
110525          False        False         False     False       False   
110526          False        False         False     False       False   

        Handcap  SMS_received  No-show  
0         False         False    False  
1         False         False    False  
2         False         False    False  
3         False         False    False  
4         False         False    False  
...         ...           ...      ...  
110522    False         False    False  
110523    False         False    False  
110524    False         False    False  
110525    False         False    False  
110526    False         False    False  

[110527 rows x 14 columns]

In [6]:
appointments[appointments.isnull().any(axis=1)]

Empty DataFrame
Columns: [PatientId, AppointmentID, Gender, ScheduledDay, AppointmentDay, Age, Neighbourhood, Scholarship, Hipertension, Diabetes, Alcoholism, Handcap, SMS_received, No-show]
Index: []

<b>No null values found in dataset</b>

In [7]:
# Importing LabelEncoder from the preprocessing
# module of the Sklearn library
from sklearn.preprocessing import LabelEncoder

# creating an instance of label Encoder
le = LabelEncoder()

# Using .fit_transform function to fit label encoder and
# return encoded label
label = le.fit_transform(appointments['Gender'])

# printing label
label


array([0, 1, 0, ..., 0, 0, 0])

In [8]:
label2 = le.fit_transform(appointments['No-show'])
label2

array([0, 0, 0, ..., 0, 0, 0])

In [9]:
# removing the columns 'Gender' and 'No-show' from appointments
appointments.drop("Gender", axis=1, inplace=True)
appointments.drop("No-show", axis=1, inplace=True)

# Appending the arrays to the dataframe
appointments['Gender'] = label
appointments['No-show'] = label2

appointments.iloc[0:10]

PatientId  AppointmentID          ScheduledDay        AppointmentDay  \
0  2.987250e+13        5642903  2016-04-29T18:38:08Z  2016-04-29T00:00:00Z   
1  5.589978e+14        5642503  2016-04-29T16:08:27Z  2016-04-29T00:00:00Z   
2  4.262962e+12        5642549  2016-04-29T16:19:04Z  2016-04-29T00:00:00Z   
3  8.679512e+11        5642828  2016-04-29T17:29:31Z  2016-04-29T00:00:00Z   
4  8.841186e+12        5642494  2016-04-29T16:07:23Z  2016-04-29T00:00:00Z   
5  9.598513e+13        5626772  2016-04-27T08:36:51Z  2016-04-29T00:00:00Z   
6  7.336882e+14        5630279  2016-04-27T15:05:12Z  2016-04-29T00:00:00Z   
7  3.449833e+12        5630575  2016-04-27T15:39:58Z  2016-04-29T00:00:00Z   
8  5.639473e+13        5638447  2016-04-29T08:02:16Z  2016-04-29T00:00:00Z   
9  7.812456e+13        5629123  2016-04-27T12:48:25Z  2016-04-29T00:00:00Z   

   Age      Neighbourhood  Scholarship  Hipertension  Diabetes  Alcoholism  \
0   62    JARDIM DA PENHA            0             1         0           0   
1   56    JARDIM DA PENHA            0             0         0           0   
2   62      MATA DA PRAIA            0             0         0           0   
3    8  PONTAL DE CAMBURI            0             0         0           0   
4   56    JARDIM DA PENHA            0             1         1           0   
5   76          REPÚBLICA            0             1         0           0   
6   23         GOIABEIRAS            0             0         0           0   
7   39         GOIABEIRAS            0             0         0           0   
8   21         ANDORINHAS            0             0         0           0   
9   19          CONQUISTA            0             0         0           0   

   Handcap  SMS_received  Gender  No-show  
0        0             0       0        0  
1        0             0       1        0  
2        0             0       0        0  
3        0             0       0        0  
4        0             0       0        0  
5        0             0       0        0  
6        0             0       0        1  
7        0             0       0        1  
8        0             0       0        0  
9        0             0       0        0



```
# This is formatted as code
```

<b>Gender:</b>: </br>
<code>&nbsp;&nbsp;&nbsp;&nbsp;</code><b>0 = F</b></br>
<code>&nbsp;&nbsp;&nbsp;&nbsp;</code><b>1 = M</b>

<b>No-show:</b>: </br>
<code>&nbsp;&nbsp;&nbsp;&nbsp;</code><b>0 = No</b></br>
<code>&nbsp;&nbsp;&nbsp;&nbsp;</code><b>1 = Yes</b>

### Exploring the data

In [10]:
print('Shape of the data:', appointments.shape)

Shape of the data: (110527, 14)


In [11]:
appointments["Gender"].value_counts()

0    71840
1    38687
Name: Gender, dtype: int64

In [12]:
appointments["SMS_received"].value_counts()

0    75045
1    35482
Name: SMS_received, dtype: int64

In [13]:
appointments["No-show"].value_counts()

0    88208
1    22319
Name: No-show, dtype: int64

#### Preparing the data for model training

In [14]:
X = appointments.iloc[:, [4, 11, 12]].values
y = appointments.iloc[:, -1].values

X

array([[62,  0,  0],
       [56,  0,  1],
       [62,  0,  0],
       ...,
       [21,  1,  0],
       [38,  1,  0],
       [54,  1,  0]], dtype=int64)

In [15]:
# Splitting the dataset into training and testing data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=0)


In [16]:
# Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
# Creating and training the K-Nearest Neighbor model using the training set
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [18]:
# Predicting the output for the test set
y_pred = classifier.predict(X_test)

### Comparing true and predicted values

In [19]:
y_test[0:70]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0])

In [20]:
y_pred[0:70]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0])

### Model evaluation

<b>Evaluating the model using the confusion matrix and accuracy score</b>

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

#### Confusion matrix

In [22]:
print('Confusion matrix:', cm)

Confusion matrix: [[23559  3012]
 [ 5774   814]]


#### Accuracy score

In [23]:
print('Accuracy on training data:', classifier.score(X_train, y_train))
print('Accuracy on test data:', classifier.score(X_test, y_test))

Accuracy on training data: 0.7350584220866508
Accuracy on test data: 0.7350342290177629


<b>Predicting a new value</b>

<b>SMS_received:</b>: </br>
<code>&nbsp;&nbsp;&nbsp;&nbsp;</code><b>0 = No</b></br>
<code>&nbsp;&nbsp;&nbsp;&nbsp;</code><b>1 = Yes</b>

<b>No-show:</b>: </br>
<code>&nbsp;&nbsp;&nbsp;&nbsp;</code><b>0 = No</b></br>
<code>&nbsp;&nbsp;&nbsp;&nbsp;</code><b>1 = Yes</b>

In [24]:
X_new = np.array([[35, 1, 1]])
pred_new = classifier.predict(X_new)
print(pred_new)

[1]


<b>The output above shows the model predict that a male patient (1) of the age of (35) having received an SMS message (1) is likely to be a No-show for their medical appointment as indicated by the output [1].</b>